baseURL = "https://gohugo.io/"
title = "StarWays"
author = "Steve Francia"
copyright = "Copyright (c) 2021 Jouad El Ouardi & Arturo Garrido"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

theme = "casper3"

[params]
  facebook = "https://facebook.com"
  twitter = "https://twitter.com"
<<<<<<< HEAD:domain/StarWays/config.toml
  github = "https://github.com/Jouad01/Proyecto_Pydevops"
  description = "La mejor pagina de compraventa de naves intergalactica"
=======
  github = "https://github.com/jonathanjanssens"
  description = "La tienda de compra y venta de naves intergaláctica"
>>>>>>> 668b06848ee14272b635ae48957e216b8b0182ea:StarWays/config.toml
  mainSections = ["post"]

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "image-credit"
    name = "Agregue su Nave"
    url = "/vender/"
    weight = 20
  [[menu.main]]
    identifier = "github-repo-theme"
    name = "stuff"
    url = "/stuff/"
    weight = 30


[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

