baseURL = "https://gohugo.io/"
title = "StarWays"
author = "Arturo & Hugo"
copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

theme = "casper3"

[params]
  facebook = "https://facebook.com"
  twitter = "https://twitter.com"
  github = "https://github.com/jonathanjanssens"
  description = "La mejor gama de transportes espaciales"
  mainSections = ["post"]

[menu]
  [[menu.main]]
    identifier = "Sobre nosotros"
    name = "Sobre nosotros"
    url = "/sobre_nosotros/"
    weight = 10
  [[menu.main]]
    identifier = "/image-credit/"
    name = "OKAY"
    url = "/image-credit/"
    weight = 20
  [[menu.main]]
    identifier = "/Vender naves/"
    name = "Vender"
    url = "/vende_tu_nave/"
    weight = 20
  [[menu.main]]
    identifier = "/Guía/"
    name = "Guía"
    url = "/guia/"
    weight = 20



[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

